apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-nodeapp
    app.kubernetes.io/part-of: test-application
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/test-nodeapp@sha256:12ec1ba9d60b9deff4a334105c87490ea96072a8445674757b9acc8a3e381e9c
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
