apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/redhat-appstudio/user-workload:jephilli-go
        name: container-image
        resources: {}
status: {}
